version: "3"
services:
  syncthing:
    image: syncthing/syncthing:latest
    container_name: syncthing
    environment:
      - PUID=1000
      - PGID=1000
      - "TZ=Europe/Warsaw"
    volumes:
      - /home/michaljp/docker/syncthing:/var/syncthing
      - /home/michaljp/webthings:/webthings
    network_mode: host
    #ports:
    #  - 8384:8384
    #  - 22000:22000
    #  - 21027:21027/udp
    restart: unless-stopped
